package com.example.pcsalt.weatherxmlparsingdemo.handler

object WeatherTags {
    const val DATA = "data"
    const val CURRENT_CONDITION = "current_condition"
    const val OBSERVATION_TIME = "observation_time"
    const val TEMP__C = "temp_C"
    const val TEMP__F = "temp_F"
    const val WEATHER_ICON_URL = "weatherIconUrl"
    const val WEATHER_DESC = "weatherDesc"
    const val UV_INDEX = "uvIndex"
    const val WEATHER = "weather"
    const val DATE = "date"
    const val MAX_TEMP_C = "maxtempC"
    const val MAX_TEMP_F = "maxtempF"
    const val MIN_TEMP_C = "mintempC"
    const val MIN_TEMP_F = "mintempF"
    const val AVG_TEMP_C = "avgtempC"
    const val AVG_TEMP_F = "avgtempF"
    const val SUN_HOUR = "sunHour"
    const val HOURLY = "hourly"
    const val TIME = "time"
    const val TEMP_C = "tempC"
    const val TEMP_F = "tempF"
    const val HUMIDITY = "humidity"
    const val FEELS_LIKE_C = "FeelsLikeC"
    const val FEELS_LIKE_F = "FeelsLikeF"
}